CXX=g++
INCLUDES=-w -Icore/ -Irtaudio/ -Istk/ -Ix-api/ -Iy-api -I/opt/local/include
FLAGS=-D__MACOSX_CORE__ $(INCLUDES) -c
LIBS=-framework CoreAudio -framework CoreMIDI -framework CoreFoundation \
	-framework IOKit -framework Carbon -framework OpenGL \
	-framework GLUT -lstdc++ -lm -L/opt/local/lib -lfluidsynth

